// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using task1_read_from_txt;

#nullable disable

namespace task1_read_from_txt.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20240704235240_createTables")]
    partial class createTables
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.6")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("task1_read_from_txt.FileComponent", b =>
                {
                    b.Property<int>("FileComponentId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("FileComponentId"));

                    b.Property<int>("Category")
                        .HasColumnType("int");

                    b.Property<string>("Data")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("FileDataId")
                        .HasColumnType("int");

                    b.Property<int>("LengthOfData")
                        .HasColumnType("int");

                    b.HasKey("FileComponentId");

                    b.HasIndex("FileDataId");

                    b.ToTable("Components");
                });

            modelBuilder.Entity("task1_read_from_txt.FileData", b =>
                {
                    b.Property<int>("FileDataId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("FileDataId"));

                    b.Property<string>("Path")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("FileDataId");

                    b.ToTable("Files");
                });

            modelBuilder.Entity("task1_read_from_txt.FileComponent", b =>
                {
                    b.HasOne("task1_read_from_txt.FileData", "FileData")
                        .WithMany("Components")
                        .HasForeignKey("FileDataId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("FileData");
                });

            modelBuilder.Entity("task1_read_from_txt.FileData", b =>
                {
                    b.Navigation("Components");
                });
#pragma warning restore 612, 618
        }
    }
}
